name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - name: Build
        run: |
          if npm run | grep -q " build"; then
            npm run build
          else
            echo "No build script found. Skipping."
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - name: Lint
        run: |
          if npm run | grep -q " lint"; then
            npm run lint
          else
            echo "No lint script found. Skipping."
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - name: Test
        env:
          CI: true
        run: |
          if npm run | grep -q " test"; then
            npm test -- --watch=false || npm test -- --watchAll=false
          else
            echo "No test script found. Skipping."
          fi

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - name: TypeScript type check
        run: |
          if [ -f tsconfig.json ]; then
            npx tsc --noEmit
          else
            echo "No tsconfig.json; skipping."
          fi

  targeted-tests:
    name: CTA and lead gen tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - name: Run CTA and lead gen tests
        env:
          CI: true
        run: npm test -- --watchAll=false --testPathPattern='home\.cta\.test\.jsx|LeadGenerationForm\.test\.jsx'
